FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY Main.java .
RUN javac Main.java
# TODO: Choose a java JRE
FROM eclipse-temurin:21-jre-alpine
# TODO:  Add the compiled java (aka bytecode, aka .class)
COPY Main.class /app/
WORKDIR /app
# TODO: Run the Java with: “java Main” command.
CMD ["java","Main"]